### ISSUE TITLE
Support monorepo structures / multiple `.gqlconfig` files

### ISSUE THREAD

**Issue by GrtDev** [Mayank1791989/gql#137]
I'm trying to use this with the `graphql-for-vscode` plugin. After some debugging I found out that the `.gqlconfig` file is expected to be in the root of the workspace. This does not work well for monorepo's where it could contain multiple packages with different graphql schemas etc.

I set up an [example to illustrate the issue here](https://github.com/GrtDev/graphql-for-vscode-mono-repo).

Any chance it could support multiple packages containing their own `.gqlconfig` files?

**Comment by Mayank1791989** [comment]
see issue https://github.com/kumarharsh/graphql-for-vscode/issues/46
