### ISSUE TITLE
How to disable rule "unique type names"?

### ISSUE THREAD

**Issue by seniv** [Mayank1791989/gql#153]
Hello everyone!
Because of I'm using https://github.com/okgrow/merge-graphql-schemas this package to merge graphql schemas, I have defined Types Query/Mutation/Subscription multiple times, and I got an error `Schema must contain unique named types but contains multiple types named "Query".graphql(syntax)`.

How I can disable this rule for these types, or disable it at all?
I've tried to disable it in `.gqlconfig`, but don't know which rule I have to disable

**Comment by Mayank1791989** [comment]
See https://github.com/kumarharsh/graphql-for-vscode/issues/92#issuecomment-386687710

**Comment by seniv** [comment]
Thanks for your answer. That's sad that i can't disable it, but for now the issue can be closed
