### ISSUE TITLE
Document that `.gqlconfig` should be in JSON format

### ISSUE THREAD

**Issue by lensbart** [Mayank1791989/gql#171]
Perhaps the README should explain that the `.gqlconfig` file must be in JSON format? If I look through the source code it seems to be parsed as such. But the example configuration file looks like a plain JavaScript object, which confused me.

Or am I wrong? Also, comments in this file seem to be permitted?

I ran into this issue when configuring syntax highlighting & code formatting for our project’s configuration files in VS Code

**Comment by kumarharsh** [comment]
It has to be in `JSON5` format, not JSON. JSON5 allows keys to be unquoted, hence resembling a JS object. I'd recommend you install a `JSON5` syntax highlighter and associate `.gqlconfig` with that extension for the future.

**Comment by lensbart** [comment]
Thanks!
