### ISSUE TITLE
Make .gqlconfig optional?

### ISSUE THREAD

**Issue by FezVrasta** [Mayank1791989/gql#87]
I think it would make sense to make .gqlconfig optional and set the default config to include anything (`**/*.gql`), doing so packages that depend on this one don't have to ask the consumers to create the gqlconfig file

**Comment by Mayank1791989** [comment]
There are so many ways people can write graphql and for that we need .gqlconfig.

**Comment by FezVrasta** [comment]
Ok, but by default couldn't it just be:

```
{
  schema: {
    files: '**/*.gql'
  }
}
```

so that out of the box it can just work and if needed people can configure it?

**Comment by Mayank1791989** [comment]
This is only the schema part what about queries?. Say for example someone using apollo js client and writing queries using js tagged template
```js
{
  schema: {
    files: '**/*.gql'
  },
  query: {
      {
         match: "path_to_apollo_files",
         parser: [ 'EmbeddedQueryParser', { startTag: 'gql`', endTag: '`' } ],
      }
  }
}
```

**Comment by FezVrasta** [comment]
The one I provided is the minimal configuration needed to make the basic functionalities of this module work (specifically for the vscode graphql syntax highlighting actually).

As said, if someone needs more config, they can add it easily creating the `.gqlconfig` file

**Comment by Mayank1791989** [comment]
If you are using graphql-for-vscode plugin for only syntax highlighting than there is no need to install this package. This package is required by plugin only If you want to enable ide features (autocomplete, linting, jump to definition etc).

**Comment by FezVrasta** [comment]
that wasn't what I experienced, but may easily be a problem with the plugin itself. Thanks for the info then.

**Comment by Mayank1791989** [comment]
Thats weird plugin should highlight your graphql code without this package if you are having problem please open issue there.
